version: '3'
services:
  # Disponible à l'adresse : http://localhost:8080/
  php-apache:
    container_name: php-apache
    build: ./docker/php-apache
    restart: always
    env_file:
      - ./docker/mysql/credentials.env
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html:z
    # MySQL doit être créée avant ce serveur
    links:
      - mysql

  # Disponible à l'adresse : http://localhost:3306
  mysql:
    container_name: mysql
    build: ./docker/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./docker/mysql/credentials.env
    environment:
      TZ: 'Europe/Paris'
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_general_ci
      # Permettre l'authentication facile pour utiliser phpMyAdmin
      #   Serveur: mysql
      #   Utilisateur: root
      #   Pas de mdp
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 8082:3306
    volumes:
      - mysql:/var/lib/mysql

  # Disponible à l'adresse : http://localhost:8081/
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8081:80
    volumes:
      - /sessions
    depends_on:
      - mysql

# Faire persister la base de données dans une volume Docker
volumes:
  mysql:
